from __future__ import annotations

"""One-off catalog deepening batch (2026-06-09).

Appends new, distinct error-catalog entries for the priority domains
ARITH / FRACT / DEC / ALGEBRA, matching the existing JSONL schema. Authored via the
Claude Code subscription ($0) — NOT the Anthropic API. Validates JSON + code
uniqueness before writing, and normalizes trailing whitespace in each file.
"""

import json
from pathlib import Path

CATALOG_DIR = Path(__file__).resolve().parent.parent / "out" / "catalog"


def _e(
    code: str,
    name: str,
    description: str,
    domain: str,
    subdomain: str,
    severity: str,
    grades: list[int],
    hint: str,
    remediation: str,
    refs: list[str] | None = None,
) -> dict[str, object]:
    return {
        "code": code,
        "name": name,
        "description": description,
        "domain_code": domain,
        "subdomain_code": subdomain,
        "severity": severity,
        "source": "LLM_GENERATED",
        "status": "DRAFT",
        "applicable_grades": grades,
        "diagnostic_hint": hint,
        "remediation": remediation,
        "references": refs or [],
    }


ARITH: list[dict[str, object]] = [
    _e("ARITH_COUNT_DOUBLE_COUNTS_OBJECT_G1", "Cuenta un objeto dos veces",
       "Al contar una colección asigna dos números a un mismo objeto, rompiendo la correspondencia uno a uno.",
       "ARITH", "COUNT", "MED", [1, 2], "El cardinal final supera la cantidad real de objetos.",
       "Reforzar la correspondencia uno a uno tocando y apartando cada objeto contado.", ["Gelman & Gallistel 1978"]),
    _e("ARITH_COUNT_ORDINAL_CARDINAL_CONFUSED_G1", "Confunde ordinal con cardinal",
       "Responde la posición (quinto) cuando se pide la cantidad total (cinco) o viceversa.",
       "ARITH", "COUNT", "LOW", [1, 2], "La respuesta mezcla posición y cantidad.",
       "Distinguir 'qué lugar ocupa' de 'cuántos hay' con actividades de fila.", ["Gelman & Gallistel 1978"]),
    _e("ARITH_COUNT_SKIP_BY_3_LOST_PATTERN_G3", "Pierde el patrón al contar de 3 en 3",
       "Al contar de 3 en 3 abandona el incremento constante a mitad de la secuencia.",
       "ARITH", "COUNT", "LOW", [3, 4], "El salto entre términos deja de ser 3.",
       "Marcar los saltos de 3 en la recta numérica y verbalizar el patrón.", []),
    _e("ARITH_COUNT_BACKWARD_DECADE_RESET_G2", "Reinicia decena al contar hacia atrás",
       "Al contar en orden descendente cruza la decena reiniciando mal (21, 20, 10).",
       "ARITH", "COUNT", "MED", [2, 3], "El cruce de decena hacia abajo salta o reinicia.",
       "Practicar conteo regresivo en la tabla del 100 fila por fila.", []),
    _e("ARITH_PLACE_VALUE_LEADING_DIGIT_ONLY_COMPARE_G3", "Compara solo por la primera cifra",
       "Decide cuál número es mayor mirando únicamente el dígito de la izquierda sin considerar la cantidad de cifras (52 mayor que 478 porque 5>4).",
       "ARITH", "PLACE_VALUE", "HIGH", [3, 4], "Ignora el largo del número al comparar.",
       "Comparar primero la cantidad de cifras y luego posición por posición.", ["Resnick & Ford 1981"]),
    _e("ARITH_PLACE_VALUE_THOUSANDS_DOT_AS_DECIMAL_G5", "Lee el punto de mil como coma decimal",
       "Interpreta el separador de miles (2.040) como si fuera una coma decimal.",
       "ARITH", "PLACE_VALUE", "MED", [5, 6], "Confunde separador de miles con parte decimal.",
       "Distinguir el rol del punto de miles frente a la coma decimal en notación chilena.", []),
    _e("ARITH_PLACE_VALUE_NUMBER_LINE_WRONG_SCALE_G3", "Ubica en recta numérica con escala errada",
       "Sitúa un número en la recta usando un intervalo o escala distinta a la marcada.",
       "ARITH", "PLACE_VALUE", "MED", [3, 4], "La posición no corresponde a la escala de la recta.",
       "Identificar el valor de cada intervalo antes de ubicar el número.", []),
    _e("ARITH_ADD_MENTAL_ADDS_TO_WRONG_PLACE_G3", "Suma mental a la posición equivocada",
       "Al sumar mentalmente agrega las unidades de un sumando a las decenas del otro (23+40 da 27).",
       "ARITH", "ADD", "MED", [3, 4], "El resultado mezcla valores de distinta posición.",
       "Descomponer por valor posicional antes de sumar mentalmente.", []),
    _e("ARITH_ADD_DECADE_COMPLEMENT_ERROR_G2", "Error al completar la decena",
       "Calcula mal cuánto falta para la decena siguiente al sumar (8 + 7 pensando 8+2=10 y luego +6).",
       "ARITH", "ADD", "LOW", [2, 3], "El complemento a la decena usado es incorrecto.",
       "Practicar complementos a 10 antes de la estrategia de completar decena.", []),
    _e("ARITH_ADD_CARRY_WRITTEN_IN_SAME_COLUMN_G3", "Escribe la llevada en la misma columna",
       "Anota el dígito que debía llevar dentro del resultado de la misma columna en lugar de pasarlo a la siguiente.",
       "ARITH", "ADD", "HIGH", [3, 4], "Una columna del resultado tiene dos cifras.",
       "Llevar la cifra excedente a la columna inmediatamente a la izquierda.", ["Brown & VanLehn 1980"]),
    _e("ARITH_SUB_BORROW_TENS_NOT_ADDED_TO_UNITS_G3", "Presta pero no agrega 10 a las unidades",
       "Decrementa la decena al pedir prestado pero no suma las 10 unidades a la columna de unidades.",
       "ARITH", "SUB", "HIGH", [3, 4], "La columna de unidades no recibe las 10 prestadas.",
       "Al pedir prestado, sumar 10 a la columna que lo recibe.", ["Brown & VanLehn 1980"]),
    _e("ARITH_SUB_DOUBLE_BORROW_G4", "Pide prestado dos veces",
       "Toma prestado más de una vez para una misma columna, decrementando de más la columna vecina.",
       "ARITH", "SUB", "MED", [4, 5], "La columna de origen baja en más de 1.",
       "Pedir prestado una sola unidad por columna cuando es necesario.", []),
    _e("ARITH_SUB_DIFFERENT_LENGTHS_MISALIGNED_G3", "Mala alineación al restar largos distintos",
       "Alinea por la izquierda minuendo y sustraendo de distinta cantidad de cifras.",
       "ARITH", "SUB", "HIGH", [3, 4], "Las unidades no quedan bajo las unidades.",
       "Alinear siempre por la derecha antes de restar.", ["VanLehn 1990"]),
    _e("ARITH_MUL_OMITS_PARTIAL_PRODUCT_G5", "Omite un producto parcial",
       "En multiplicación multidígito deja de escribir una fila completa de producto parcial.",
       "ARITH", "MUL", "HIGH", [5, 6], "Faltan filas de productos parciales antes de sumar.",
       "Generar un producto parcial por cada dígito del segundo factor.", ["VanLehn 1990"]),
    _e("ARITH_MUL_DISTRIBUTES_OVER_ADDITION_WRONG_G5", "Distribuye mal sobre una suma",
       "Calcula a×(b+c) como a×b+c, multiplicando solo el primer término.",
       "ARITH", "MUL", "HIGH", [5, 6], "La distribución no alcanza a todos los sumandos.",
       "Multiplicar el factor por cada término del paréntesis.", []),
    _e("ARITH_MUL_DOUBLES_INSTEAD_OF_SQUARES_G5", "Duplica en vez de elevar al cuadrado",
       "Calcula n×n como n+n (5×5 da 10).",
       "ARITH", "MUL", "MED", [5, 6], "El resultado coincide con el doble y no con el cuadrado.",
       "Diferenciar duplicar (n+n) de multiplicar por sí mismo (n×n).", []),
    _e("ARITH_DIV_BY_ONE_GIVES_ONE_G3", "Dividir por 1 da 1",
       "Calcula n÷1 = 1 en lugar de n.",
       "ARITH", "DIV", "MED", [3, 4], "El cociente es 1 sin importar el dividendo.",
       "Repartir entre 1 deja la cantidad intacta.", []),
    _e("ARITH_DIV_BY_ITSELF_GIVES_ZERO_G4", "Dividir un número por sí mismo da 0",
       "Calcula n÷n = 0 en vez de 1.",
       "ARITH", "DIV", "MED", [4, 5], "El cociente de un número entre sí mismo es 0.",
       "Repartir n entre n grupos da 1 por grupo.", []),
    _e("ARITH_DIV_SUBTRACTS_DIVISOR_ONCE_G4", "Resta el divisor una sola vez",
       "Interpreta la división como restar el divisor una vez del dividendo.",
       "ARITH", "DIV", "HIGH", [4, 5], "El resultado es dividendo menos divisor.",
       "La división es resta reiterada hasta agotar el dividendo.", []),
    _e("ARITH_DIV_QUOTIENT_DIGITS_REVERSED_G5", "Invierte el orden de las cifras del cociente",
       "Escribe las cifras del cociente en orden inverso al obtenido.",
       "ARITH", "DIV", "MED", [5, 6], "El cociente tiene las cifras correctas en orden invertido.",
       "Escribir cada cifra del cociente sobre la posición que se está dividiendo.", []),
    _e("ARITH_FACT_RECALL_MULT_NEAR_MISS_G3", "Producto básico cercano pero incorrecto",
       "Recupera un producto de la tabla próximo al correcto (6×7 da 48).",
       "ARITH", "FACT_RECALL", "LOW", [3, 4], "El producto difiere en un múltiplo pequeño del correcto.",
       "Reforzar tablas con productos vecinos y patrones de la tabla.", []),
    _e("ARITH_FACT_RECALL_SUBTRACT_FROM_TEN_ERROR_G2", "Error al restar desde 10",
       "Recupera mal restas básicas apoyadas en el 10 (10-6 da 5).",
       "ARITH", "FACT_RECALL", "LOW", [2, 3], "La diferencia desde 10 está desviada.",
       "Usar el marco de 10 para visualizar la resta.", []),
]

FRACT: list[dict[str, object]] = [
    _e("FRACT_REPR_COUNTS_PARTS_ACROSS_WHOLES_G4", "Cuenta partes a través de varios enteros",
       "Al representar una fracción cuenta partes de más de un entero como si fueran del mismo todo.",
       "FRACT", "REPR", "HIGH", [4, 5], "El denominador agrupa partes de distintos enteros.",
       "Definir claramente cuál es el entero de referencia antes de contar partes.", ["Mack 1990"]),
    _e("FRACT_REPR_NUMBER_LINE_COUNTS_MARKS_G4", "Cuenta marcas en vez de intervalos",
       "Ubica una fracción en la recta contando las marcas en lugar de los intervalos.",
       "FRACT", "REPR", "MED", [4, 5], "El denominador surge del número de marcas, no de partes.",
       "Contar los espacios iguales entre 0 y 1, no las marcas.", []),
    _e("FRACT_EQUIV_MULT_DIFFERENT_FACTORS_G5", "Amplifica con factores distintos",
       "Multiplica numerador y denominador por números diferentes al buscar una equivalente.",
       "FRACT", "EQUIV", "HIGH", [5, 6], "El factor aplicado al numerador no es el del denominador.",
       "Usar el mismo factor en numerador y denominador.", ["Behr et al. 1983"]),
    _e("FRACT_REDUCE_DIVIDES_DIFFERENT_NUMBERS_G6", "Simplifica dividiendo por números distintos",
       "Divide numerador y denominador por divisores diferentes al simplificar.",
       "FRACT", "REDUCE", "HIGH", [6, 7], "El cociente del numerador no usa el mismo divisor del denominador.",
       "Dividir ambos términos por un mismo divisor común.", []),
    _e("FRACT_REDUCE_CANCELS_ACROSS_SUM_G7", "Cancela un término a través de una suma",
       "Tacha un sumando del numerador con uno del denominador en una expresión con sumas.",
       "FRACT", "REDUCE", "HIGH", [7, 8], "Se cancela un término que está sumando, no multiplicando.",
       "Solo se simplifican factores comunes de todo el numerador y denominador.", []),
    _e("FRACT_COMPARE_LARGER_NUM_IS_LARGER_G5", "Mayor numerador es mayor fracción",
       "Con denominadores distintos, supone que la fracción de numerador mayor es mayor.",
       "FRACT", "COMPARE", "HIGH", [5, 6], "Compara solo numeradores ignorando el denominador.",
       "Llevar a denominador común o comparar con un referente antes de decidir.", ["Behr et al. 1983"]),
    _e("FRACT_COMPARE_BENCHMARK_HALF_IGNORED_G6", "Ignora el referente de un medio",
       "No usa 1/2 ni 1 como referentes para comparar y decide al azar.",
       "FRACT", "COMPARE", "MED", [6, 7], "No hay comparación con referentes intermedios.",
       "Comparar cada fracción con 1/2 y con 1 como puntos de referencia.", ["Behr et al. 1983"]),
    _e("FRACT_ADDSUB_SAME_DENOM_ADDS_DENOM_G5", "Suma también los denominadores con igual denominador",
       "Con denominadores iguales suma numeradores y además suma los denominadores.",
       "FRACT", "ADDSUB", "HIGH", [5, 6], "El denominador del resultado se duplicó.",
       "Con igual denominador se conserva el denominador y se suman los numeradores.", ["Mack 1990"]),
    _e("FRACT_ADDSUB_KEEPS_LARGER_DENOM_NO_CONVERT_G6", "Usa el mayor denominador sin convertir",
       "Toma el denominador mayor como común pero no amplifica la otra fracción.",
       "FRACT", "ADDSUB", "HIGH", [6, 7], "Una de las fracciones no fue convertida al común.",
       "Amplificar ambas fracciones al denominador común antes de operar.", []),
    _e("FRACT_MUL_WHOLE_TIMES_FRACTION_ADDS_WHOLE_G6", "Entero por fracción suma el entero",
       "Calcula n × a/b como (n+a)/b en lugar de (n×a)/b.",
       "FRACT", "MUL", "HIGH", [6, 7], "El numerador resulta de sumar el entero, no de multiplicar.",
       "Multiplicar el entero por el numerador y conservar el denominador.", []),
    _e("FRACT_MUL_EXPECTS_LARGER_PRODUCT_G6", "Espera que el producto sea mayor",
       "Supone que multiplicar fracciones siempre da un resultado mayor que los factores.",
       "FRACT", "MUL", "MED", [6, 7], "Rechaza un producto menor que los factores.",
       "Visualizar que una parte de una parte es menor que el todo.", ["Behr et al. 1983"]),
    _e("FRACT_DIV_INVERTS_BOTH_FRACTIONS_G7", "Invierte ambas fracciones",
       "Al dividir aplica el recíproco a las dos fracciones.",
       "FRACT", "DIV", "HIGH", [7, 8], "Aparecen invertidas tanto dividendo como divisor.",
       "Invertir únicamente el divisor y multiplicar.", []),
    _e("FRACT_DIV_EXPECTS_SMALLER_RESULT_G7", "Espera que dividir dé menor resultado",
       "Supone que dividir fracciones siempre reduce el valor (rechaza cocientes mayores que el dividendo).",
       "FRACT", "DIV", "MED", [7, 8], "Descarta un cociente mayor que el dividendo.",
       "Dividir por una fracción menor que 1 produce un resultado mayor.", []),
    _e("FRACT_MIXED_ADD_NOT_REGROUPED_G6", "Suma de mixtos no reagrupa fracción impropia",
       "Al sumar mixtos deja la parte fraccionaria mayor que 1 sin convertir en entero.",
       "FRACT", "MIXED", "MED", [6, 7], "La parte fraccionaria del resultado supera la unidad.",
       "Convertir la fracción impropia resultante en entero más fracción.", []),
    _e("FRACT_MIXED_MULT_PART_BY_PART_G7", "Multiplica mixtos parte por parte",
       "Multiplica enteros entre sí y fracciones entre sí sin convertir a impropias.",
       "FRACT", "MIXED", "HIGH", [7, 8], "El producto omite los términos cruzados entero-fracción.",
       "Convertir cada mixto a fracción impropia antes de multiplicar.", []),
    _e("FRACT_MIXED_IMPROPER_TO_MIXED_REMAINDER_ERROR_G6", "Resto erróneo al pasar de impropia a mixto",
       "Convierte una fracción impropia en mixto con resto incorrecto.",
       "FRACT", "MIXED", "MED", [6, 7], "El entero por el denominador más el resto no reconstruye el numerador.",
       "Dividir numerador entre denominador: cociente es el entero y resto es el nuevo numerador.", []),
    _e("FRACT_EQUIV_DECIMAL_ROUND_MISMATCH_G6", "Declara equivalencia por decimales redondeados",
       "Afirma que dos fracciones son equivalentes porque sus decimales redondeados coinciden.",
       "FRACT", "EQUIV", "MED", [6, 7], "La equivalencia se basa en una aproximación decimal.",
       "Verificar equivalencia por amplificación o simplificación exacta.", []),
    _e("FRACT_REPR_DENOM_FROM_SHADED_ONLY_G4", "Denominador desde las partes pintadas",
       "Usa la cantidad de partes pintadas como denominador en lugar del total de partes.",
       "FRACT", "REPR", "HIGH", [4, 5], "El denominador coincide con las partes pintadas.",
       "El denominador es el total de partes iguales del entero.", ["Mack 1990"]),
]

DEC: list[dict[str, object]] = [
    _e("DEC_REPR_READS_AS_TWO_INTEGERS_G5", "Lee el decimal como dos enteros",
       "Lee 3,5 como 'tres y cinco' tratando la parte entera y decimal como números independientes.",
       "DEC", "REPR", "MED", [5, 6], "Nombra el decimal como dos números separados.",
       "Leer la parte decimal según su valor posicional (tres coma cinco = tres y cinco décimos).", []),
    _e("DEC_REPR_FRACTION_NAMED_WRONG_PLACE_G5", "Nombra mal la fracción decimal",
       "Asocia 0,3 a 3/100 en lugar de 3/10 por confundir la posición.",
       "DEC", "REPR", "HIGH", [5, 6], "El denominador potencia de 10 no corresponde a la posición.",
       "Décimos van en la primera posición tras la coma; centésimos en la segunda.", []),
    _e("DEC_COMPARE_NEGATIVE_BY_MAGNITUDE_G7", "Compara decimales negativos por magnitud",
       "Considera mayor el decimal negativo de mayor valor absoluto (-0,7 mayor que -0,2).",
       "DEC", "COMPARE", "HIGH", [7, 8], "El orden de los negativos está invertido.",
       "En negativos, el de menor valor absoluto es el mayor.", []),
    _e("DEC_COMPARE_PADS_LEFT_OF_FRACTION_G5", "Rellena ceros a la izquierda de la parte decimal",
       "Para comparar agrega ceros antes de la parte decimal en vez de a la derecha (0,5 vs 0,05).",
       "DEC", "COMPARE", "MED", [5, 6], "El relleno de ceros altera el valor de la parte decimal.",
       "Igualar la cantidad de decimales agregando ceros a la derecha.", []),
    _e("DEC_ADD_PARTS_SEPARATE_CARRY_LOST_G5", "Suma partes por separado y pierde la llevada",
       "Suma parte entera y parte decimal por separado sin propagar la llevada entre ellas.",
       "DEC", "ADD", "HIGH", [5, 6], "La llevada de la parte decimal no llega a las unidades.",
       "Alinear por la coma y sumar como un solo número propagando la llevada.", []),
    _e("DEC_SUB_BORROW_ACROSS_POINT_ERROR_G6", "Préstamo a través de la coma mal resuelto",
       "Al restar maneja mal el préstamo entre la parte decimal y la entera.",
       "DEC", "SUB", "HIGH", [6, 7], "El préstamo no cruza correctamente la coma.",
       "Tratar el número como un todo alineado por la coma al pedir prestado.", []),
    _e("DEC_MUL_DECIMAL_COUNT_WRONG_G6", "Cuenta mal los decimales del producto",
       "Multiplica como enteros pero ubica la coma con una cantidad incorrecta de decimales.",
       "DEC", "MUL", "HIGH", [6, 7], "El número de decimales del producto no es la suma de los factores.",
       "Sumar la cantidad de decimales de ambos factores para ubicar la coma.", []),
    _e("DEC_MUL_EXPECTS_LARGER_PRODUCT_G6", "Espera que el producto sea mayor",
       "Supone que multiplicar por un decimal menor que 1 aumenta el valor.",
       "DEC", "MUL", "MED", [6, 7], "Rechaza un producto menor que el factor original.",
       "Multiplicar por un número entre 0 y 1 reduce el valor.", []),
    _e("DEC_DIV_QUOTIENT_POINT_MISPLACED_G6", "Coma mal ubicada en el cociente",
       "Coloca la coma del cociente en una posición incorrecta tras dividir.",
       "DEC", "DIV", "HIGH", [6, 7], "La coma del cociente no se alinea con la del dividendo.",
       "Subir la coma del dividendo a la misma posición en el cociente.", []),
    _e("DEC_DIV_BY_DECIMAL_EXPECTS_SMALLER_G7", "Espera menor resultado al dividir por decimal",
       "Supone que dividir por un decimal menor que 1 reduce el valor.",
       "DEC", "DIV", "MED", [7, 8], "Descarta un cociente mayor que el dividendo.",
       "Dividir por un número entre 0 y 1 aumenta el resultado.", []),
    _e("DEC_DIV_DROPS_DIVIDEND_DECIMALS_G6", "Ignora los decimales del dividendo",
       "Divide considerando solo la parte entera del dividendo y descarta sus decimales.",
       "DEC", "DIV", "HIGH", [6, 7], "El resultado corresponde a dividir solo la parte entera.",
       "Incluir todos los decimales del dividendo en la división.", []),
    _e("DEC_ROUND_CASCADE_NOT_PROPAGATED_G6", "No propaga el redondeo en cadena",
       "Al redondear un 9 no propaga el acarreo a la posición anterior (1,99 a 1,90).",
       "DEC", "ROUND", "MED", [6, 7], "El redondeo de un 9 no incrementa la cifra previa.",
       "Cuando el dígito redondeado pasa de 9, propagar el acarreo.", []),
    _e("DEC_ROUND_USES_ALL_FOLLOWING_DIGITS_G6", "Redondea mirando todos los dígitos siguientes",
       "Decide el redondeo observando varias cifras posteriores en lugar de solo la inmediata.",
       "DEC", "ROUND", "MED", [6, 7], "El criterio usa más de un dígito a la derecha.",
       "Redondear según el dígito inmediatamente siguiente a la posición pedida.", []),
    _e("DEC_FRACT_CONV_NON_POWER_TEN_DENOM_G7", "Convierte ignorando denominador no potencia de 10",
       "Convierte una fracción a decimal asumiendo denominador potencia de 10 cuando no lo es.",
       "DEC", "FRACT_CONV", "HIGH", [7, 8], "El decimal no corresponde a dividir numerador entre denominador.",
       "Convertir dividiendo numerador entre denominador, no leyendo posiciones.", []),
    _e("DEC_FRACT_CONV_PERIODIC_TRUNCATED_WRONG_G7", "Trunca mal un decimal periódico",
       "Al convertir una fracción de decimal periódico corta la cifra en una posición incorrecta.",
       "DEC", "FRACT_CONV", "MED", [7, 8], "El periodo se corta sin criterio o en la posición equivocada.",
       "Identificar el periodo y representarlo o redondear según lo pedido.", []),
]

ALGEBRA: list[dict[str, object]] = [
    _e("ALGEBRA_EXPR_VARIABLE_AS_LABEL_G7", "Trata la variable como etiqueta",
       "Interpreta 3m como '3 metros' (m unidad) y no como 3 por m.",
       "ALGEBRA", "EXPR", "HIGH", [7, 8], "La letra se usa como rótulo y no como número desconocido.",
       "La variable representa un número; 3m significa 3 veces m.", ["Küchemann 1981"]),
    _e("ALGEBRA_EXPR_LACK_OF_CLOSURE_G7", "No acepta una expresión como respuesta",
       "Rechaza dejar a+b como resultado y fuerza un único término.",
       "ALGEBRA", "EXPR", "MED", [7, 8], "Combina términos no semejantes para 'cerrar' la respuesta.",
       "Una expresión como a+b ya es una respuesta válida si no hay términos semejantes.", ["Collis 1975"]),
    _e("ALGEBRA_MONOMIAL_MULT_ADDS_COEFFICIENTS_G8", "Multiplica monomios sumando coeficientes",
       "Al multiplicar monomios suma los coeficientes en lugar de multiplicarlos.",
       "ALGEBRA", "MONOMIAL", "HIGH", [8, 9], "El coeficiente del producto es la suma, no el producto.",
       "Multiplicar coeficientes y sumar exponentes de igual base.", []),
    _e("ALGEBRA_MONOMIAL_POWER_MULT_COEFF_BY_EXP_G8", "Confunde potencia con producto por exponente",
       "Interpreta x^3 como 3x, multiplicando la base por el exponente.",
       "ALGEBRA", "MONOMIAL", "HIGH", [8, 9], "La potencia se trató como una multiplicación.",
       "x^3 es x·x·x, no 3·x.", []),
    _e("ALGEBRA_EQ_LINEAR_OPERATES_ONE_SIDE_ONLY_G8", "Opera en un solo lado de la ecuación",
       "Aplica una operación a un solo miembro y no al otro, rompiendo el equilibrio.",
       "ALGEBRA", "EQ_LINEAR", "HIGH", [8, 9], "La igualdad deja de mantenerse tras el paso.",
       "Toda operación se aplica a ambos miembros de la ecuación.", []),
    _e("ALGEBRA_EQ_LINEAR_FRACTION_CLEARS_ONE_TERM_G8", "Elimina denominador en un solo término",
       "Multiplica por el denominador común pero solo afecta a un término de la ecuación.",
       "ALGEBRA", "EQ_LINEAR", "HIGH", [8, 9], "Quedan términos sin multiplicar por el denominador.",
       "Multiplicar todos los términos de ambos miembros por el denominador común.", []),
    _e("ALGEBRA_INEQ_LINEAR_SOLUTION_AS_POINT_G9", "Da la solución como un único valor",
       "Resuelve una inecuación y entrega un solo número en lugar de un intervalo.",
       "ALGEBRA", "INEQ_LINEAR", "MED", [9, 10], "La respuesta es un punto y no un conjunto.",
       "La solución de una inecuación es un intervalo de valores.", []),
    _e("ALGEBRA_SYSTEM2X2_ADDS_WITHOUT_ALIGNING_G8", "Suma ecuaciones sin alinear variables",
       "Suma o resta las ecuaciones sin alinear los términos de cada variable.",
       "ALGEBRA", "SYSTEM_2X2", "HIGH", [8, 9], "Se combinan términos de variables distintas.",
       "Alinear términos semejantes antes de sumar o restar ecuaciones.", []),
    _e("ALGEBRA_EXPAND_NEG_SIGN_NOT_DISTRIBUTED_G8", "No distribuye el signo negativo",
       "Calcula -(a+b) como -a+b, sin cambiar el signo del segundo término.",
       "ALGEBRA", "EXPAND", "HIGH", [8, 9], "El segundo término conserva su signo tras el menos.",
       "El signo negativo cambia el signo de todos los términos del paréntesis.", []),
    _e("ALGEBRA_FACTOR_GCF_DROPS_UNIT_TERM_G9", "Pierde el término 1 al factorizar",
       "Factoriza el factor común y omite el 1 que queda (x^2+x como x·x).",
       "ALGEBRA", "FACTOR", "HIGH", [9, 10], "El producto factorizado no reconstruye la expresión.",
       "Al sacar factor común, dejar 1 cuando el término se factoriza completo.", []),
    _e("ALGEBRA_FACTOR_TRINOMIAL_SIGN_ERROR_G10", "Signos errados en factores del trinomio",
       "Encuentra los números correctos pero les asigna signos equivocados al factorizar.",
       "ALGEBRA", "FACTOR", "MED", [10, 11], "Al expandir los factores no se recupera el trinomio.",
       "Verificar signos de modo que el producto dé el término independiente y la suma el lineal.", []),
    _e("ALGEBRA_EQ_QUAD_ZERO_PRODUCT_NONZERO_RHS_G10", "Aplica producto nulo con segundo miembro no nulo",
       "Iguala cada factor a un valor cuando la ecuación no está igualada a cero.",
       "ALGEBRA", "EQ_QUAD", "HIGH", [10, 11], "Usa el producto nulo sin tener 0 en un miembro.",
       "Llevar la ecuación a la forma = 0 antes de aplicar el producto nulo.", []),
    _e("ALGEBRA_EQ_QUAD_COMPLETING_SQUARE_HALF_ERROR_G11", "Error al completar el cuadrado",
       "Calcula mal (b/2)^2 al completar cuadrado.",
       "ALGEBRA", "EQ_QUAD", "MED", [11, 12], "El término agregado no es el cuadrado de la mitad del coeficiente lineal.",
       "Agregar (b/2)^2 a ambos miembros para completar el cuadrado.", []),
    _e("ALGEBRA_POLY_DEGREE_FROM_TERM_COUNT_G10", "Confunde grado con número de términos",
       "Determina el grado del polinomio contando sus términos.",
       "ALGEBRA", "POLY", "MED", [10, 11], "El grado informado coincide con la cantidad de términos.",
       "El grado es el mayor exponente de la variable, no el número de términos.", []),
    _e("ALGEBRA_EXPR_TRANSLATE_LESS_THAN_ORDER_G7", "Invierte el orden en 'menos que'",
       "Traduce 'a es 5 menos que b' como a-5=b en lugar de a=b-5.",
       "ALGEBRA", "EXPR", "MED", [7, 8], "El orden de la resta queda invertido respecto al enunciado.",
       "Identificar la cantidad de referencia: 'menos que b' resta a b.", ["Clement 1982"]),
    _e("ALGEBRA_EQ_LINEAR_MOVES_FACTOR_AS_TERM_G8", "Pasa un factor como término",
       "Despeja moviendo un coeficiente que multiplica como si estuviera sumando.",
       "ALGEBRA", "EQ_LINEAR", "HIGH", [8, 9], "Un factor pasa al otro miembro restando en vez de dividiendo.",
       "Lo que multiplica pasa dividiendo; lo que suma pasa restando.", []),
]

FILES: dict[str, list[dict[str, object]]] = {
    "01-arith.jsonl": ARITH,
    "03-fract.jsonl": FRACT,
    "04-dec.jsonl": DEC,
    "06-algebra.jsonl": ALGEBRA,
}


def main() -> None:
    # Global uniqueness check across all existing files.
    existing_codes: set[str] = set()
    for path in CATALOG_DIR.glob("*.jsonl"):
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                existing_codes.add(json.loads(line)["code"])

    new_codes: set[str] = set()
    total_added = 0
    for filename, entries in FILES.items():
        path = CATALOG_DIR / filename
        kept = [
            line for line in path.read_text(encoding="utf-8").splitlines() if line.strip()
        ]
        for entry in entries:
            code = str(entry["code"])
            if code in existing_codes or code in new_codes:
                raise SystemExit(f"DUPLICATE CODE: {code}")
            new_codes.add(code)
            kept.append(json.dumps(entry, ensure_ascii=False))
        path.write_text("\n".join(kept) + "\n", encoding="utf-8")
        total_added += len(entries)
        print(f"{filename}: +{len(entries)} -> {len(kept)} entries")

    grand_total = sum(
        1
        for p in CATALOG_DIR.glob("*.jsonl")
        for ln in p.read_text(encoding="utf-8").splitlines()
        if ln.strip()
    )
    print(f"Added {total_added} new entries. Catalog total now: {grand_total}")


if __name__ == "__main__":
    main()
